version: 2.1

executors:
  python:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<< parameters.version >>-node

      - image: peterjclaw/sr-dev-ldap
        # Set an explicit name for the LDAP server host so that it can bind to
        # that distinctly from "localhost", which otherwise causes issues. See
        # https://github.com/osixia/docker-openldap/issues/373 for what the
        # failure looks like.
        name: sr-dev-ldap

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-test:
          matrix:
            parameters:
              version: ["3.6", "3.7", "3.8", "3.9"]

jobs:
  build-test:
    parameters:
      version:
        type: string

    executor:
      name: python
      version: << parameters.version >>

    steps:
      - checkout

      - run: git submodule update --init --recursive

      # Set up a cached virtualenv in which to install dependencies
      - restore_cache:
          name: Restore dependency cache
          key: deps-venv-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install base dependencies
          command: sudo apt install libsasl2-dev python3-dev libldap2-dev libssl-dev ldap-utils sqlite3
      - run:
          name: Create virtualenv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - save_cache:
          name: Save dependency cache
          key: deps-venv-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"

      - run:
          name: Install JS dependencies
          command: sudo npm install -g jasmine-node

      - run:
          name: Configure LDAP connection
          command: |
            echo "[ldap]" > nemesis/libnemesis/libnemesis/srusers/local.ini
            echo "host = sr-dev-ldap" >> nemesis/libnemesis/libnemesis/srusers/local.ini
            echo "password = 123456" >> nemesis/libnemesis/libnemesis/srusers/local.ini

      - run:
          name: Setup Sqlite database
          command: ./nemesis/scripts/make_db.sh

      - run:
          name: Wait for LDAP server to be running
          command: |
            set +e  # we use exit codes for control flow
            for x in $(seq 60)
            do
              ldapsearch -h sr-dev-ldap -D 'cn=Manager,o=sr' -w 123456 -b 'o=sr'
              if [ $? -ne 0 ]
              then
                sleep 0.5
              else
                exit 0
              fi
            done

      - run:
          name: Run tests
          command: |
            . venv/bin/activate

            # Run the development server in the background
            python nemesis/app.py 2>&1 > server-log.txt &
            server_pid=$!
            trap "kill -SIGINT $server_pid" exit INT TERM

            ./run-tests
